### PR TITLE
Support sorting enchanted books

### PR DESCRIPTION
**Pull request by BillyGalbreath**

### CODE REVIEW

**Comment by me4502** [comment]
Does this have any side effects?

**Comment by BillyGalbreath** [comment]
None that I've experienced so far.

**Comment by BillyGalbreath** [comment]
Cleaned it up so its not so rough on the eyes with those nasty instanceof/null checks

**Comment by me4502** [comment]
Thanks, would you be able to squash this?

**Comment by BillyGalbreath** [comment]
Not gonna lie.. I dont know how to squash commits.

**Comment by me4502** [comment]
Found out I can do it via github without erasing you as the committer, thanks.

**Comment by BillyGalbreath** [comment]
I figured it out. Squashed :)

**Pull request merged**
