### PR TITLE
PT-BR Translation of CraftBook

### PR DESCRIPTION
**Pull request by DouglasB31**
**Don't replace REPLACE.MD**
I'm new to GitHub.

### CODE REVIEW

**Comment by me4502** [comment]
Hi,

Thanks - but a PR isn't the correct way of adding translations to CraftBook 3. 

Could you please upload the file to a gist, and then put it on this wiki page? http://wiki.sk89q.com/wiki/CraftBook/Languages

Thanks.

**Comment by DouglasB31** [comment]
I didn't find the link to create an account on the wiki. But here is it:
```
File: http://pastebin.com/raw/G6hxfs1t
Author: Douglas Biazus
Version: 3.9u10
```
Thank U me4502

**Comment by wizjany** [comment]
wiki is currently under lockdown, but i've gone ahead and added the file. you didn't provide a gist so if you need to update it you will need to ask me again.

**Comment by DouglasB31** [comment]
I'm asking again. The translation was wrongly made, wasn't converted to ANSI, I thought that was needed to put / before accents WTF. I tried to make a new one, but isn't working.
https://gist.github.com/DouglasB31/76aae775123401b14d9cc44ca72e16fd

**Comment by wizjany** [comment]
I've updated the wiki links to point to your gist. I'm not sure how the file encoding works unfortunately.

**Comment by DouglasB31** [comment]
Same. I saw the russian translation of CraftBook with a lot of different characters, without latin characters and running fine. Why the translation that I've made doesn't works? THX for adding my translation.

**Pull request closed without merging**
